Config = {
    ["UsingLoader"]     = false,
    
    ["UsingESX"]        = true,
    ["UsingESX_V1.2.0"] = false,
    ["UsingKashacters"] = false,
    ["CashAccountName"] = "money",
    ["BankAccountName"] = "bank",
}

Controls = {
  Focus = 185,
  Grab = 24,
}

furni = {}

furni.objects = {
  ["沙發"] = {
    [1] = { ["object"] = "miss_rub_couch_01", ["price"] = 2000, ["name"] = "舊式沙發" },
    [2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 3000, ["name"] = "三座椅子" },
    [3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 13500, ["name"] = "舊式單座沙發" },
    [4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 2000, ["name"] = "老三座沙發" },
    [5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 2000, ["name"] = "舊條紋沙發" },
    [6] = { ["object"] = "v_res_d_armchair", ["price"] = 2000, ["name"] = "舊式單座沙發黃色" },
    [7] = { ["object"] = "v_res_fh_sofa", ["price"] = 33000, ["name"] = "轉角沙發" },
    [8] = { ["object"] = "v_res_mp_sofa", ["price"] = 33000, ["name"] = "轉角沙發2" },
    [9] = { ["object"] = "v_res_d_sofa", ["price"] = 3000, ["name"] = "沙發1" },
    [10] = { ["object"] = "v_res_j_sofa", ["price"] = 3000, ["name"] = "沙發2" },
    [11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 3000, ["name"] = "沙發3" },
    [12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 3000, ["name"] = "沙發 4" },
    [13] = { ["object"] = "v_res_r_sofa", ["price"] = 3000, ["name"] = "沙發 5" },
    [14] = { ["object"] = "v_res_tre_sofa", ["price"] = 3000, ["name"] = "沙發 6" },
    [15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 3000, ["name"] = "沙發 7" },
    [16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 3000, ["name"] = "沙發 8" },
    [17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 3000, ["name"] = "沙發 9" },
    [18] = { ["object"] = "v_res_tt_sofa", ["price"] = 3000, ["name"] = "沙發 10" },
    [19] = { ["object"] = "prop_rub_couch02", ["price"] = 3000, ["name"] = "沙發 11" },
    [20] = { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 13500, ["name"] = "腳凳 1" },
    [21] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 13500, ["name"] = "腳凳 2" },
  },

  ["椅子"] = {
    [1] = { ["object"] = "v_res_d_highchair", ["price"] = 3000, ["name"] = "高腳椅" },
    [2] = { ["object"] = "v_res_fa_chair01", ["price"] = 3000, ["name"] = "椅子" },
    [3] = { ["object"] = "v_res_fa_chair02", ["price"] = 3000, ["name"] = "椅子" },
    [4] = { ["object"] = "v_res_fh_barcchair", ["price"] = 3000, ["name"] = "高腳椅" },
    [5] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 3000, ["name"] = "餐椅 1" },
    [6] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 3000, ["name"] = "餐椅 2" },
    [7] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 3000, ["name"] = "餐椅 3" },
    [8] = { ["object"] = "v_res_fh_easychair", ["price"] = 3000, ["name"] = "椅子" },
    [9] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 3000, ["name"] = "凳" },
    [10] = { ["object"] = "v_res_fh_singleseat", ["price"] = 3000, ["name"] = "高腳椅" },
    [11] = { ["object"] = "v_res_jarmchair", ["price"] = 3000, ["name"] = "扶手椅" },
    [12] = { ["object"] = "v_res_j_dinechair", ["price"] = 3000, ["name"] = "餐椅" },
    [13] = { ["object"] = "v_res_j_stool", ["price"] = 3000, ["name"] = "糞便" },
    [14] = { ["object"] = "v_res_mbchair", ["price"] = 3000, ["name"] = "MB椅" },
    [15] = { ["object"] = "v_res_m_armchair", ["price"] = 3000, ["name"] = "扶手椅" },
    [16] = { ["object"] = "v_res_m_dinechair", ["price"] = 3000, ["name"] = "餐椅" },
    [17] = { ["object"] = "v_res_study_chair", ["price"] = 3000, ["name"] = "學習椅" },
    [18] = { ["object"] = "v_res_trev_framechair", ["price"] = 3000, ["name"] = "框架椅" },
    [19] = { ["object"] = "v_res_tre_chair", ["price"] = 3000, ["name"] = "椅子" },
    [20] = { ["object"] = "v_res_tre_officechair", ["price"] = 3000, ["name"] = "辦公椅" },
    [21] = { ["object"] = "v_res_tre_stool", ["price"] = 3000, ["name"] = "凳" },
    [22] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 3000, ["name"] = "凳皮" },
    [23] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 3000, ["name"] = "凳子斯庫茲" },
    [24] = { ["object"] = "v_med_p_deskchair", ["price"] = 3000, ["name"] = "課桌椅" },
    [25] = { ["object"] = "v_med_p_easychair", ["price"] = 3000, ["name"] = "安樂椅" },
    [26] = { ["object"] = "v_med_whickerchair1", ["price"] = 3000, ["name"] = "藤椅" },
    [27] = { ["object"] = "prop_direct_chair_01", ["price"] = 3000, ["name"] = "直椅1" },
    [28] = { ["object"] = "prop_direct_chair_02", ["price"] = 3000, ["name"] = "直椅2" },
    [29] = { ["object"] = "prop_yacht_lounger", ["price"] = 3000, ["name"] = "遊艇座椅1" },
    [30] = { ["object"] = "prop_yacht_seat_01", ["price"] = 3000, ["name"] = "遊艇座椅 2" },
    [31] = { ["object"] = "prop_yacht_seat_02", ["price"] = 3000, ["name"] = "遊艇座椅 3" },
    [32] = { ["object"] = "prop_yacht_seat_03", ["price"] = 3000, ["name"] = "遊艇座椅 4" },
    [33] = { ["object"] = "v_ret_chair_white", ["price"] = 1200, ["name"] = "白色椅子" },
    [34] = { ["object"] = "v_ret_chair", ["price"] = 1200, ["name"] = "椅子" },
    [35] = { ["object"] = "v_ret_ta_stool", ["price"] = 1200, ["name"] = "TA凳" },
    [36] = { ["object"] = "prop_cs_office_chair", ["price"] = 1200, ["name"] = "辦公椅" },
  },

  ["床"] = {
    [1] = { ["object"] = "v_res_d_bed", ["price"] = 3000, ["name"] = "D床" },  
    [2] = { ["object"] = "v_res_lestersbed", ["price"] = 3000, ["name"] = "L床" }, 
    [3] = { ["object"] = "v_res_mbbed", ["price"] = 3000, ["name"] = "MB床" }, 
    [4] = { ["object"] = "v_res_mdbed", ["price"] = 3000, ["name"] = "MD床" }, 
    [5] = { ["object"] = "v_res_msonbed", ["price"] = 3000, ["name"] = "梅森床" },  
    [6] = { ["object"] = "v_res_tre_bed1", ["price"] = 3000, ["name"] = "T床" }, 
    [7] = { ["object"] = "v_res_tre_bed2", ["price"] = 3000, ["name"] = "T床2" }, 
    [8] = { ["object"] = "v_res_tt_bed", ["price"] = 3000, ["name"] = "TT床" },
    [9] = { ["object"] = "apa_mp_h_bed_double_08", ["price"] = 3000, ["name"] = "雙人床" },  
    [10] = { ["object"] = "apa_mp_h_bed_double_09", ["price"] = 3000, ["name"] = "雙人床2" },
    [11] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 3000, ["name"] = "雙人床3" },
    [12] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 12000, ["name"] = "桌子床" },
    [13] = { ["object"] = "gr_prop_bunker_bed_01", ["price"] = 3500, ["name"] = "單人床" },
  },

  ["通用 #1"] = {
    [1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 1200, ["name"] = "豆袋1" },
    [2] = { ["object"] = "v_res_cherubvase", ["price"] = 2000, ["name"] = "白色花瓶" },
    [3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 2000, ["name"] = "填充牆" },
    [4] = { ["object"] = "v_res_d_ramskull", ["price"] = 2000, ["name"] = "項目" },
    [5] = { ["object"] = "v_res_d_whips", ["price"] = 2000, ["name"] = "鞭子" },
    [6] = { ["object"] = "v_res_fashmag1", ["price"] = 2000, ["name"] = "雜誌" },
    [7] = { ["object"] = "v_res_fashmagopen", ["price"] = 2000, ["name"] = "打開的雜誌" },
    [8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 2000, ["name"] = "馬格·提迪" },
    [9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 2000, ["name"] = "瑜伽墊1" },
    [10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 2000, ["name"] = "瑜伽墊2" },
    [11] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 2000, ["name"] = "須後水" },
    [12] = { ["object"] = "v_res_fh_flowersa", ["price"] = 2000, ["name"] = "花卉" },
    [13] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 2000, ["name"] = "果盤" },
    [14] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 2000, ["name"] = "洗衣籃" },
    [15] = { ["object"] = "v_res_fh_pouf", ["price"] = 2000, ["name"] = "厚圓椅墊" },
    [16] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 2000, ["name"] = "雕塑" },
    [17] = { ["object"] = "v_res_j_magrack", ["price"] = 2000, ["name"] = "雜誌架" },
    [18] = { ["object"] = "v_res_jewelbox", ["price"] = 2000, ["name"] = "珠寶盒" },
    [19] = { ["object"] = "v_res_mbbin", ["price"] = 2000, ["name"] = "箱子" },
    [20] = { ["object"] = "v_res_mbowlornate", ["price"] = 2000, ["name"] = "華麗碗" },
    [21] = { ["object"] = "v_res_mbronzvase", ["price"] = 2000, ["name"] = "青銅花瓶" },
    [22] = { ["object"] = "v_res_mchalkbrd", ["price"] = 2000, ["name"] = "粉筆板" },
    [23] = { ["object"] = "v_res_mddresser", ["price"] = 2000, ["name"] = "梳妝台" },
    [24] = { ["object"] = "v_res_mplinth", ["price"] = 2000, ["name"] = "底座" },
    [25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 2000, ["name"] = "煙灰缸" },
    [26] = { ["object"] = "v_res_m_candle", ["price"] = 2000, ["name"] = "蠟燭" },
    [27] = { ["object"] = "v_res_m_candlelrg", ["price"] = 2000, ["name"] = "大蠟燭" },
    [28] = { ["object"] = "v_res_m_kscales", ["price"] = 2000, ["name"] = "秤" },
    [29] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 2000, ["name"] = "床枕" },
    [30] = { ["object"] = "apa_p_h_acc_artwallm_04", ["price"] = 2000, ["name"] = "壁畫 1" },
    [31] = { ["object"] = "apa_p_h_acc_artwallm_03", ["price"] = 2000, ["name"] = "壁畫 2" },
    [32] = { ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 2000, ["name"] = "壁畫 3" },
    [33] = { ["object"] = "apa_p_h_acc_artwalll_04", ["price"] = 2000, ["name"] = "壁畫 4" },
    [34] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 2000, ["name"] = "壁畫 5" },
    [35] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 2000, ["name"] = "地毯 1" },
    [36] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 2000, ["name"] = "地毯 2" },
    [37] = { ["object"] = "apa_mp_h_acc_rugwools_03", ["price"] = 2000, ["name"] = "地毯 3" },
    [38] = { ["object"] = "hei_heist_str_sideboardl_05", ["price"] = 1200, ["name"] = "電視櫃"}
  },

  ["通用 #2"] = {
    [1] = { ["object"] = "prop_a4_pile_01", ["price"] = 1200, ["name"] = "隔板" },
    [2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 1200, ["name"] = "40 oz" },
    [3] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 1200, ["name"] = "啤酒" },
    [4] = { ["object"] = "prop_aviators_01", ["price"] = 1200, ["name"] = "飛行員眼鏡" },
    [5] = { ["object"] = "prop_barry_table_detail", ["price"] = 1200, ["name"] = "詳情" },
    [6] = { ["object"] = "prop_beer_box_01", ["price"] = 1200, ["name"] = "啤酒" },
    [7] = { ["object"] = "prop_binoc_01", ["price"] = 1200, ["name"] = "望遠鏡" },
    [8] = { ["object"] = "prop_blox_spray", ["price"] = 1200, ["name"] = "Blox噴霧" },
    [9] = { ["object"] = "prop_bongos_01", ["price"] = 1200, ["name"] = "手鼓" },
    [10] = { ["object"] = "prop_bong_01", ["price"] = 1200, ["name"] = "Bong" },
    [11] = { ["object"] = "prop_boombox_01", ["price"] = 1200, ["name"] = "喇叭褲" },
    [12] = { ["object"] = "prop_bowl_crisps", ["price"] = 1200, ["name"] = "碗薯片" },
    [13] = { ["object"] = "prop_candy_pqs", ["price"] = 1200, ["name"] = "糖果" },
    [14] = { ["object"] = "prop_carrier_bag_01", ["price"] = 1200, ["name"] = "購物袋" },
    [15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 1200, ["name"] = "陶瓷壺" },
    [16] = { ["object"] = "prop_cigar_pack_01", ["price"] = 1200, ["name"] = "雪茄包 1" },
    [17] = { ["object"] = "prop_cigar_pack_02", ["price"] = 1200, ["name"] = "雪茄包 2" },
    [18] = { ["object"] = "prop_cs_beer_box", ["price"] = 1200, ["name"] = "啤酒盒 2" },
    [19] = { ["object"] = "prop_cs_binder_01", ["price"] = 1200, ["name"] = "活頁夾" },
    [20] = { ["object"] = "prop_cs_bs_cup", ["price"] = 1200, ["name"] = "杯子" },
    [21] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 1200, ["name"] = "信封" },
    [22] = { ["object"] = "prop_cs_champ_flute", ["price"] = 1200, ["name"] = "長笛" },
    [23] = { ["object"] = "prop_cs_duffel_01", ["price"] = 1200, ["name"] = "行李袋" },
    [24] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["name"] = "DVD" },
    [25] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["name"] = "DVD盒" },
    [26] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 1200, ["name"] = "電影捲軸" },
    [27] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 1200, ["name"] = "盲" },
    [28] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 1200, ["name"] = "袋" },
    [29] = { ["object"] = "prop_cs_ironing_board", ["price"] = 1200, ["name"] = "燙衣板" },
    [30] = { ["object"] = "prop_cs_katana_01", ["price"] = 1200, ["name"] = "武士刀" },
    [31] = { ["object"] = "prop_cs_kettle_01", ["price"] = 1200, ["name"] = "水壺" },
    [32] = { ["object"] = "prop_cs_lester_crate", ["price"] = 1200, ["name"] = "箱" },
    [33] = { ["object"] = "prop_cs_petrol_can", ["price"] = 1200, ["name"] = "汽油罐" },
    [34] = { ["object"] = "prop_cs_sack_01", ["price"] = 1200, ["name"] = "麻袋" },
    [35] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 1200, ["name"] = "汽水瓶" },
    [36] = { ["object"] = "prop_cs_script_bottle", ["price"] = 1200, ["name"] = "汽水瓶 2" },
    [37] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 1200, ["name"] = "垃圾袋" },
    [38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 1200, ["name"] = "威士忌酒瓶" },
    [39] = { ["object"] = "prop_sh_bong_01", ["price"] = 1200, ["name"] = "Bong 2" },
    [40] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 1200, ["name"] = "花生" },
    [41] = { ["object"] = "prop_tumbler_01", ["price"] = 1200, ["name"] = "不倒翁" },
  },

  ["通用 #3"] = {
    [1] = { ["object"] = "v_ret_csr_bin", ["price"] = 1200, ["name"] = "CSR Bin" },
    [2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 1200, ["name"] = "籃" },
    [3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 1200, ["name"] = "GC袋 1" },
    [4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 1200, ["name"] = "GC袋 2" },
    [5] = { ["object"] = "v_ret_gc_bin", ["price"] = 1200, ["name"] = "垃圾箱" },
    [6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 1200, ["name"] = "收銀機" },
    [7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 1200, ["name"] = "GC主席 01" },
    [8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 1200, ["name"] = "GC主席 02" },
    [9] = { ["object"] = "v_ret_gc_clock", ["price"] = 1200, ["name"] = "時鐘" },
    [10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 1200, ["name"] = "產品 1" },
    [11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 1200, ["name"] = "產品 2" },
    [12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 1200, ["name"] = "產品 3" },
    [13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 1200, ["name"] = "產品 4" },
    [14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 1200, ["name"] = "產品 5" },
    [15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 1200, ["name"] = "產品 6" },
    [16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 1200, ["name"] = "高清單元 1" },
    [17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 1200, ["name"] = "高清單元 2" },
    [18] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 1200, ["name"] = "冰箱" },
    [19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 1200, ["name"] = "袋 1" },
    [20] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 1200, ["name"] = "袋 2" },
    [21] = { ["object"] = "v_ret_ta_book1", ["price"] = 1200, ["name"] = "書 1" },
    [22] = { ["object"] = "v_ret_ta_book2", ["price"] = 1200, ["name"] = "書 2" },
    [23] = { ["object"] = "v_ret_ta_book3", ["price"] = 1200, ["name"] = "書 3" },
    [24] = { ["object"] = "v_ret_ta_book4", ["price"] = 1200, ["name"] = "書 4" },
    [25] = { ["object"] = "v_ret_ta_camera", ["price"] = 1200, ["name"] = "相機" },
    [26] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 1200, ["name"] = "急救" },
    [27] = { ["object"] = "v_ret_ta_hero", ["price"] = 1200, ["name"] = "Hero" },
    [28] = { ["object"] = "v_ret_ta_mag1", ["price"] = 1200, ["name"] = "雜誌 1" },
    [29] = { ["object"] = "v_ret_ta_mag2", ["price"] = 1200, ["name"] = "雜誌 2" },
    [30] = { ["object"] = "v_ret_ta_skull", ["price"] = 1200, ["name"] = "頭骨" },
    [31] = { ["object"] = "prop_acc_guitar_01", ["price"] = 1200, ["name"] = "吉他" },
    [32] = { ["object"] = "prop_amb_handbag_01", ["price"] = 1200, ["name"] = "手提包" },
    [33] = { ["object"] = "prop_attache_case_01", ["price"] = 1200, ["name"] = "文件夾" },
    [34] = { ["object"] = "prop_big_bag_01", ["price"] = 1200, ["name"] = "大袋" },
    [35] = { ["object"] = "prop_bonesaw", ["price"] = 1200, ["name"] = "骨鋸" },
    [36] = { ["object"] = "prop_cs_fertilizer", ["price"] = 1200, ["name"] = "肥料" },
    [37] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 1200, ["name"] = "購物包" },
    [38] = { ["object"] = "prop_cs_vial_01", ["price"] = 1200, ["name"] = "小瓶" },
    [39] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 1200, ["name"] = "布娃娃" }, 
  },

  ["通用 #4"] = {
    [1] = { ["object"] = "prop_dummy_01", ["price"] = 1200, ["name"] = "假人" },
    [2] = { ["object"] = "prop_egg_clock_01", ["price"] = 1200, ["name"] = "鐘" },
    [3] = { ["object"] = "prop_el_guitar_01", ["price"] = 1200, ["name"] = "電子吉他1" },
    [4] = { ["object"] = "prop_el_guitar_02", ["price"] = 1200, ["name"] = "電子吉他2" },
    [5] = { ["object"] = "prop_el_guitar_03", ["price"] = 1200, ["name"] = "電子吉他2" },
    [6] = { ["object"] = "prop_feed_sack_01", ["price"] = 1200, ["name"] = "飼料袋" },
    [7] = { ["object"] = "prop_floor_duster_01", ["price"] = 1200, ["name"] = "地拖" },
    [8] = { ["object"] = "prop_fruit_basket", ["price"] = 1200, ["name"] = "水果籃" },
    [9] = { ["object"] = "prop_f_duster_02", ["price"] = 1200, ["name"] = "除塵器" },
    [10] = { ["object"] = "prop_grapes_02", ["price"] = 1200, ["name"] = "葡萄" },
    [11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 1200, ["name"] = "酒店時鐘" },
    [12] = { ["object"] = "prop_idol_case_01", ["price"] = 1200, ["name"] = "偶像套" },
    [13] = { ["object"] = "prop_jewel_02a", ["price"] = 1200, ["name"] = "珠寶" },
    [14] = { ["object"] = "prop_jewel_02b", ["price"] = 1200, ["name"] = "珠寶" },
    [15] = { ["object"] = "prop_jewel_02c", ["price"] = 1200, ["name"] = "珠寶" },
    [16] = { ["object"] = "prop_jewel_03a", ["price"] = 1200, ["name"] = "珠寶" },
    [17] = { ["object"] = "prop_jewel_03b", ["price"] = 1200, ["name"] = "珠寶" },
    [18] = { ["object"] = "prop_jewel_04a", ["price"] = 1200, ["name"] = "珠寶" },
    [19] = { ["object"] = "prop_jewel_04b", ["price"] = 1200, ["name"] = "珠寶" },
    [20] = { ["object"] = "prop_j_disptray_01", ["price"] = 1200, ["name"] = "展示架" },
    [21] = { ["object"] = "prop_j_disptray_01b", ["price"] = 1200, ["name"] = "展示架" },
    [22] = { ["object"] = "prop_j_disptray_02", ["price"] = 1200, ["name"] = "展示架" },
    [23] = { ["object"] = "prop_j_disptray_03", ["price"] = 1200, ["name"] = "展示架" },
    [24] = { ["object"] = "prop_j_disptray_04", ["price"] = 1200, ["name"] = "展示架" },
    [25] = { ["object"] = "prop_j_disptray_04b", ["price"] = 1200, ["name"] = "展示架" },
    [26] = { ["object"] = "prop_j_disptray_05", ["price"] = 1200, ["name"] = "展示架" },
    [27] = { ["object"] = "prop_j_disptray_05b", ["price"] = 1200, ["name"] = "展示架" },
    [28] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 1200, ["name"] = "綠幕" },
    [29] = { ["object"] = "prop_ld_handbag", ["price"] = 1200, ["name"] = "手提包" },
    [30] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 1200, ["name"] = "油桶" },
    [31] = { ["object"] = "prop_ld_keypad_01", ["price"] = 1200, ["name"] = "鍵盤1" },
    [32] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 1200, ["name"] = "鍵盤2" },
    [33] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 1200, ["name"] = "手提箱1" },
    [34] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 1200, ["name"] = "手提箱2" },
    [35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 1200, ["name"] = "手提箱3"},
    [36] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 1200, ["name"] = "泰迪熊" },
    [37] = { ["object"] = "prop_paper_bag_01", ["price"] = 1200, ["name"] = "紙袋" },
    [38] = { ["object"] = "prop_shopping_bags01", ["price"] = 1200, ["name"] = "購物袋" },
    [39] = { ["object"] = "prop_shopping_bags02", ["price"] = 1200, ["name"] = "購物袋2" },
    [40] = { ["object"] = "prop_yoga_mat_01", ["price"] = 1200, ["name"] = "瑜伽墊1" },
    [41] = { ["object"] = "prop_yoga_mat_02", ["price"] = 1200, ["name"] = "瑜伽墊2" },
    [42] = { ["object"] = "prop_yoga_mat_03", ["price"] = 1200, ["name"] = "瑜伽墊3" },
    [43] = { ["object"] = "p_ld_sax", ["price"] = 1200, ["name"] = "Saxophone" },
    [44] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 1200, ["name"] = "足球" },
    [45] = { ["object"] = "p_watch_01", ["price"] = 1200, ["name"] = "錶 1" },
    [46] = { ["object"] = "p_watch_02", ["price"] = 1200, ["name"] = "錶 2" },
    [47] = { ["object"] = "p_watch_03", ["price"] = 1200, ["name"] = "錶 3" },
    [48] = { ["object"] = "p_watch_04", ["price"] = 1200, ["name"] = "錶 4" },
    [49] = { ["object"] = "p_watch_05", ["price"] = 1200, ["name"] = "錶 5" },
    [51] = { ["object"] = "p_watch_06", ["price"] = 1200, ["name"] = "錶 6" },
  },

  ["小東西"] = {
    [1] = { ["object"] = "v_res_r_figcat", ["price"] = 2000, ["name"] = "貓玩偶" },
    [2] = { ["object"] = "v_res_r_figclown", ["price"] = 2000, ["name"] = "小丑玩偶" },
    [3] = { ["object"] = "v_res_r_figauth2", ["price"] = 2000, ["name"] = "證書" },
    [4] = { ["object"] = "v_res_r_figfemale", ["price"] = 2000, ["name"] = "人偶 1" },
    [5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 2000, ["name"] = "人偶 2" },
    [6] = { ["object"] = "v_res_r_figgirl", ["price"] = 2000, ["name"] = "人偶 3" },
    [7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 2000, ["name"] = "人偶 4" },
    [8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 2000, ["name"] = "柱" },
    [9] = { ["object"] = "v_res_r_figpillar", ["price"] = 2000, ["name"] = "柱" },
    [10] = { ["object"] = "v_res_r_teapot", ["price"] = 2000, ["name"] = "茶壺" },
    [11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 2000, ["name"] = "雕塑 1" },
    [12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 2000, ["name"] = "雕塑 2" },
    [13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 2000, ["name"] = "雕塑 3" },
    [14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 2000, ["name"] = "雕塑 4" },
    [15] = { ["object"] = "v_res_skateboard", ["price"] = 2000, ["name"] = "滑板" },
    [16] = { ["object"] = "v_res_sketchpad", ["price"] = 2000, ["name"] = "畫板" },
    [17] = { ["object"] = "v_res_tissues", ["price"] = 2000, ["name"] = "紙巾" },
    [18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 2000, ["name"] = "籃" },
    [19] = { ["object"] = "v_res_tre_bin", ["price"] = 2000, ["name"] = "箱子" },
    [20] = { ["object"] = "v_res_tre_cushiona", ["price"] = 2000, ["name"] = "坐墊 1" },
    [21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 2000, ["name"] = "坐墊 2" },
    [22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 2000, ["name"] = "坐墊 3" },
    [23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 2000, ["name"] = "坐墊 4" },
    [24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 2000, ["name"] = "坐墊 5" },
    [25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 2000, ["name"] = "坐墊 6" },
    [26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 2000, ["name"] = "果盤" },
    [27] = { ["object"] = "v_med_p_sideboard", ["price"] = 2000, ["name"] = "餐邊櫃" },
    [28] = { ["object"] = "prop_idol_01", ["price"] = 1200, ["name"] = "偶像 1" },
    [29] = { ["object"] = "p_cs_cuffs_02_s", ["price"] = 1200, ["name"] = "袖口" },
    [30] = { ["object"] = "prop_cs_dildo_01", ["price"] = 1200, ["name"] = "假狗 1" },
    [31] = { ["object"] = "v_res_d_dildo_a", ["price"] = 1200, ["name"] = "假狗 2" },
    [32] = { ["object"] = "v_res_d_dildo_b", ["price"] = 1200, ["name"] = "假狗 3" },
    [33] = { ["object"] = "v_res_d_dildo_c", ["price"] = 1200, ["name"] = "假狗 4" },
    [34] = { ["object"] = "v_res_d_lube", ["price"] = 1200, ["name"] = "潤滑油" },
    [35] = { ["object"] = "v_ret_gc_trays", ["price"] = 1200, ["name"] = "桌面托盤" },
    [36] = { ["object"] = "v_res_filebox01", ["price"] = 1200, ["name"] = "檔案盒" },
  },

  ["儲存櫃"] = {
    [1] = { ["object"] = "v_res_cabinet", ["price"] = 13000, ["name"] = "大櫃子" },
    [2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 13000, ["name"] = "梳妝台" },
    [3] = { ["object"] = "v_res_d_sideunit", ["price"] = 13000, ["name"] = "小櫃子 1" },
    [4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 13000, ["name"] = "小櫃子 2" },
    [5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 13000, ["name"] = "小櫃子 3" },
    [6] = { ["object"] = "v_res_mbbedtable", ["price"] = 13000, ["name"] = "床頭櫃" },
    [7] = { ["object"] = "v_res_j_tvstand", ["price"] = 13000, ["name"] = "電視組合" },
    [8] = { ["object"] = "v_res_mbdresser", ["price"] = 13000, ["name"] = "梳妝台" },
    [9] = { ["object"] = "v_res_mbottoman", ["price"] = 13000, ["name"] = "Long腳櫃" },
    [10] = { ["object"] = "v_res_mconsolemod", ["price"] = 13000, ["name"] = "櫃子" },
    [11] = { ["object"] = "v_res_mcupboard", ["price"] = 13000, ["name"] = "衣櫃" },
    [12] = { ["object"] = "v_res_mdchest", ["price"] = 13000, ["name"] = "櫃子" },
    [13] = { ["object"] = "v_res_msoncabinet", ["price"] = 13000, ["name"] = "組合櫃" },
    [14] = { ["object"] = "v_res_m_armoire", ["price"] = 13000, ["name"] = "衣櫃" },
    [15] = { ["object"] = "v_res_m_sidetable", ["price"] = 13000, ["name"] = "梳妝台" },
    [16] = { ["object"] = "v_res_son_desk", ["price"] = 13000, ["name"] = "書桌" },
    [17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 13000, ["name"] = "床頭櫃" },
    [18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 13000, ["name"] = "床頭櫃 2" },
    [19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 13000, ["name"] = "文件櫃" },
    [20] = { ["object"] = "v_res_tre_storagebox", ["price"] = 13000, ["name"] = "儲物箱" },
    [21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 13000, ["name"] = "儲物櫃" },
    [22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 13000, ["name"] = "衣櫃" },
    [23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 13000, ["name"] = "書櫃" },
    [24] = { ["object"] = "prop_devin_box_closed", ["price"] = 1200, ["name"] = "儲物櫃 2" },
    [25] = { ["object"] = "prop_mil_crate_01", ["price"] = 1200, ["name"] = "武器箱 1" },
    [26] = { ["object"] = "prop_mil_crate_02", ["price"] = 1200, ["name"] = "武器箱 2" },
    [27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 11200, ["name"] = "保險櫃" },
  },

  ["電器"] = {
    [1] = { ["object"] = "prop_trailr_fridge", ["price"] = 2000, ["name"] = "老冰箱" },
    [2] = { ["object"] = "v_res_fh_speaker", ["price"] = 2000, ["name"] = "揚聲器" },
    [3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 2000, ["name"] = "揚聲器底座" },
    [4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 2000, ["name"] = "床頭鐘" },
    [5] = { ["object"] = "v_res_fa_phone", ["price"] = 2000, ["name"] = "電話" },
    [6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 2000, ["name"] = "塔扇" },
    [7] = { ["object"] = "v_res_fa_fan", ["price"] = 2000, ["name"] = "風扇" },
    [8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 2000, ["name"] = "大屏幕" },
    [9] = { ["object"] = "v_res_lest_monitor", ["price"] = 2000, ["name"] = "CCTV" },
    [10] = { ["object"] = "v_res_tre_mixer", ["price"] = 2000, ["name"] = "混合器" },
    [11] = { ["object"] = "prop_cs_cctv", ["price"] = 1200, ["name"] = "中央電視台" },
    [12] = { ["object"] = "prop_ld_lap_top", ["price"] = 1200, ["name"] = "筆記本電腦" },
    [13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 1200, ["name"] = "螢幕" },
    [14] = { ["object"] = "xm_prop_x17_tv_flat_02", ["price"] = 3500, ["name"] = "平板電視" },
    [15] = { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 12000, ["name"] = "電視機1" },
    [16] = { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 12000, ["name"] = "電視機2" },
    [17] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 12000, ["name"] = "電視機3" },
    [18] = { ["object"] = "bkr_prop_clubhouse_jukebox_02a", ["price"] = 12000, ["name"] = "自動點唱機" },
    [19] = { ["object"] = "bkr_prop_weed_fan_floor_01a", ["price"] = 2000, ["name"] = "落地風扇" },
    [20] = { ["object"] = "prop_cs_keyboard_01", ["price"] = 2000, ["name"] = "鍵盤" },
    [21] = { ["object"] = "ex_mp_h_acc_coffeemachine_01", ["price"] = 3500, ["name"] = "咖啡機" },
  },


  ["燈具"] = {
    [1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 1200, ["name"] = "檯燈 1" },
    [2] = { ["object"] = "v_res_desklamp", ["price"] = 1200, ["name"] = "檯燈 2" },
    [3] = { ["object"] = "v_res_d_lampa", ["price"] = 1200, ["name"] = "檯燈 3" },
    [4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 1200, ["name"] = "燈 1" },
    [5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 1200, ["name"] = "座地燈" },
    [6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 1200, ["name"] = "燈 2" },
    [7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 1200, ["name"] = "燈 3" },
    [8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 1200, ["name"] = "燈 4" },
    [9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 1200, ["name"] = "床燈" },
    [10] = { ["object"] = "v_res_mplanttongue", ["price"] = 1200, ["name"] = "植物舌頭燈" },
    [11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 1200, ["name"] = "檯燈 4" },
    [12] = { ["object"] = "v_res_m_lampstand", ["price"] = 1200, ["name"] = "燈座 1" },
    [13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 1200, ["name"] = "燈座 2" },
    [14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 1200, ["name"] = "檯燈 5" },
    [15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 1200, ["name"] = "吊風扇" },
    [16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 1200, ["name"] = "高燈" },
    [17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 1200, ["name"] = "壁燈" },
    [18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 1200, ["name"] = "GC燈" },
    [19] = { ["object"] = "prop_dummy_light", ["price"] = 1200, ["name"] = "Flickering Light" },
    [20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 1200, ["name"] = "牆側燈" },
    [21] = { ["object"] = "V_44_D_emis", ["price"] = 1200, ["name"] = "Test Light" },
  },


  ["檯"] = {
    [1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 3500, ["name"] = "咖啡桌 1" },
    [2] = { ["object"] = "v_res_d_roundtable", ["price"] = 3500, ["name"] = "圓桌" },
    [3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 3500, ["name"] = "小桌" },
    [4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 3500, ["name"] = "桌 A" },
    [5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 3500, ["name"] = "桌 B" },
    [6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 3500, ["name"] = "桌 C" },
    [7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 3500, ["name"] = "餐桌" },
    [8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 3500, ["name"] = "咖啡桌 2" },
    [9] = { ["object"] = "v_res_j_lowtable", ["price"] = 3500, ["name"] = "矮桌" },
    [10] = { ["object"] = "v_res_mdbedtable", ["price"] = 3500, ["name"] = "床頭櫃" },
    [11] = { ["object"] = "v_res_mddesk", ["price"] = 3500, ["name"] = "檯" },
    [12] = { ["object"] = "v_res_msidetblemod", ["price"] = 3500, ["name"] = "圓桌 2" },
    [13] = { ["object"] = "v_res_m_console", ["price"] = 3500, ["name"] = "長檯" },
    [14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 3500, ["name"] = "圓桌 3" },
    [15] = { ["object"] = "v_res_m_h_console", ["price"] = 3500, ["name"] = "長檯 2" },
    [16] = { ["object"] = "v_res_m_stool", ["price"] = 3500, ["name"] = "矮檯 2" },
    [17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 3500, ["name"] = "檯 2" },
    [18] = { ["object"] = "v_res_tre_table2", ["price"] = 3500, ["name"] = "檯 3" },
    [19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 3500, ["name"] = "電視檯" },
    [20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 3500, ["name"] = "電視檯(高)" },
    [21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 3500, ["name"] = "中型咖啡桌" },
    [22] = { ["object"] = "v_med_p_desk", ["price"] = 3500, ["name"] = "中型桌" },
    [23] = { ["object"] = "prop_yacht_table_01", ["price"] = 1200, ["name"] = "遊艇桌 1" },
    [24] = { ["object"] = "prop_yacht_table_02", ["price"] = 1200, ["name"] = "遊艇桌 2" },
    [25] = { ["object"] = "prop_yacht_table_03", ["price"] = 1200, ["name"] = "遊艇桌 3" },
    [26] = { ["object"] = "v_ret_csr_table", ["price"] = 1200, ["name"] = "CSR 檯" },
    [27] = { ["object"] = "hei_heist_din_table_06", ["price"] = 1200, ["name"] = "餐桌椅" },
  },

  ["植物"] = {
    [1] = { ["object"] = "prop_fib_plant_01", ["price"] = 900, ["name"] = "盆栽" },
    [2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["name"] = "盆栽 2" },    
    [3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["name"] = "盆栽 3" }, 
    [4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["name"] = "盆栽 4" }, 
    [5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["name"] = "盆栽 5" }, 
    [6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["name"] = "盆栽 6" },  
    [7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["name"] = "盆栽 7" },  
    [8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["name"] = "盆栽 8" },  
    [9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["name"] = "盆栽 9" }, 
    [10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["name"] = "盆栽 10" }, 
    [11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["name"] = "盆栽 11" }, 
    [12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["name"] = "盆栽 12" }, 
    [13] = { ["object"] = "v_ret_flowers", ["price"] = 1200, ["name"] = "花瓶" },
    [14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 1200, ["name"] = "花瓶 1" },
    [15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 1200, ["name"] = "花瓶 2" },
    [16] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 1200, ["name"] = "花瓶 3" },
    [17] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 1200, ["name"] = "花瓶 4" },
    [18] = { ["object"] = "xm_prop_x17_xmas_tree_int", ["price"] = 3500, ["name"] = "聖誕樹" },
  },

  ["廚房"] = {
    [1] = { ["object"] = "prop_washer_01", ["price"] = 900, ["name"] = "洗衣機 1" },
    [2] = { ["object"] = "prop_washer_02", ["price"] = 900, ["name"] = "洗衣機 2" },
    [3] = { ["object"] = "prop_washer_03", ["price"] = 900, ["name"] = "洗衣機 3" },
    [4] = { ["object"] = "prop_washing_basket_01", ["price"] = 900, ["name"] = "洗衣籃" },
    [5] = { ["object"] = "v_res_fridgemoda", ["price"] = 900, ["name"] = "雪櫃 1" },
    [6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 900, ["name"] = "雪櫃 2" },
    [7] = { ["object"] = "prop_fridge_01", ["price"] = 900, ["name"] = "雪櫃 3" },
    [8] = { ["object"] = "prop_fridge_03", ["price"] = 900, ["name"] = "雪櫃 4" },
    [9] = { ["object"] = "prop_cooker_03", ["price"] = 900, ["name"] = "爐灶" },
    [10] = { ["object"] = "prop_micro_01", ["price"] = 900, ["name"] = "微波爐 1" },
    [11] = { ["object"] = "prop_micro_02", ["price"] = 900, ["name"] = "微波爐 2" },
    [12] = { ["object"] = "prop_wok", ["price"] = 900, ["name"] = "鍋" },
    [13] = { ["object"] = "v_res_cakedome", ["price"] = 900, ["name"] = "蛋糕盤" },
    [14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 900, ["name"] = "砧板" },
    [15] = { ["object"] = "v_res_mutensils", ["price"] = 900, ["name"] = "廚具" },
    [16] = { ["object"] = "v_res_pestle", ["price"] = 900, ["name"] = "杵" },
    [17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 900, ["name"] = "紙捲 1" },
    [18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 900, ["name"] = "紙捲 2" },
    [19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 900, ["name"] = "鍋 1" },
    [20] = { ["object"] = "v_ret_fh_pot02", ["price"] = 900, ["name"] = "鍋 2" },
    [21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 900, ["name"] = "鍋 3" },
    [22] = { ["object"] = "prop_pot_03", ["price"] = 900, ["name"] = "鍋 4" },
    [23] = { ["object"] = "prop_pot_04", ["price"] = 900, ["name"] = "鍋 5" },
    [24] = { ["object"] = "prop_pot_05", ["price"] = 900, ["name"] = "鍋 6" },
    [25] = { ["object"] = "prop_pot_06", ["price"] = 900, ["name"] = "鍋 7" },
    [26] = { ["object"] = "prop_pot_rack", ["price"] = 900, ["name"] = "鍋架" },
    [27] = { ["object"] = "prop_kitch_juicer", ["price"] = 900, ["name"] = "榨汁機" },
  },


  ["浴室"] = {
    [1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 1200, ["name"] = "馬桶 1" },
    [2] = { ["object"] = "prop_toilet_01", ["price"] = 1200, ["name"] = "馬桶 2" },
    [3] = { ["object"] = "prop_toilet_02", ["price"] = 1200, ["name"] = "馬桶 3" },
    [4] = { ["object"] = "prop_sink_02", ["price"] = 1200, ["name"] = "洗滌槽 1" },
    [5] = { ["object"] = "prop_sink_04", ["price"] = 1200, ["name"] = "洗滌槽 2" },
    [6] = { ["object"] = "prop_sink_05", ["price"] = 1200, ["name"] = "洗滌槽 3" },
    [7] = { ["object"] = "prop_sink_06", ["price"] = 1200, ["name"] = "洗滌槽 4" },
    [8] = { ["object"] = "prop_soap_disp_01", ["price"] = 1200, ["name"] = "皂液機" },
    [9] = { ["object"] = "prop_shower_rack_01", ["price"] = 1200, ["name"] = "淋浴架" },
    [10] = { ["object"] = "prop_handdry_01", ["price"] = 1200, ["name"] = "乾手機 1" },
    [11] = { ["object"] = "prop_handdry_02", ["price"] = 1200, ["name"] = "乾手機 2" },
    [12] = { ["object"] = "prop_towel_rail_01", ["price"] = 1200, ["name"] = "毛巾架 1" },
    [13] = { ["object"] = "prop_towel_rail_02", ["price"] = 1200, ["name"] = "毛巾架 2" },
    [14] = { ["object"] = "prop_towel_01", ["price"] = 1200, ["name"] = "毛巾 1" },
    [15] = { ["object"] = "v_res_mbtowel", ["price"] = 1200, ["name"] = "Tow毛巾e毛巾l 2" },
    [16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 1200, ["name"] = "毛巾 3" },
    [17] = { ["object"] = "v_res_mbath", ["price"] = 1200, ["name"] = "浴缸" },
    [18] = { ["object"] = "v_res_mbsink", ["price"] = 1200, ["name"] = "洗手盆" },
  },

  ["醫療"] = {
    [1] = { ["object"] = "v_med_barrel", ["price"] = 2000, ["name"] = "水塔" },
    [2] = { ["object"] = "v_med_apecrate", ["price"] = 2000, ["name"] = "寵物籠" },
    [3] = { ["object"] = "v_med_apecratelrg", ["price"] = 2000, ["name"] = "寵物籠(大)" },
    [4] = { ["object"] = "v_med_bed1", ["price"] = 2000, ["name"] = "病床 1" },
    [5] = { ["object"] = "v_med_bed2", ["price"] = 2000, ["name"] = "病床 2" },
    [6] = { ["object"] = "v_med_bedtable", ["price"] = 2000, ["name"] = "病床檯" },
    [7] = { ["object"] = "v_med_bench1", ["price"] = 2000, ["name"] = "櫃 1" },
    [8] = { ["object"] = "v_med_bench2", ["price"] = 2000, ["name"] = "櫃 2" },
    [9] = { ["object"] = "v_med_benchcentr", ["price"] = 2000, ["name"] = "櫃 3" },
    [10] = { ["object"] = "v_med_benchset1", ["price"] = 2000, ["name"] = "台上物品" },
    [11] = { ["object"] = "v_med_bigtable", ["price"] = 2000, ["name"] = "大檯" },
    [12] = { ["object"] = "v_med_bin", ["price"] = 900, ["name"] = "垃圾桶" },
    [13] = { ["object"] = "v_med_centrifuge1", ["price"] = 2000, ["name"] = "離心器" },
    [14] = { ["object"] = "v_med_cooler", ["price"] = 2000, ["name"] = "散熱器" },
    [15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 2000, ["name"] = "熒幕" },
    [16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 2000, ["name"] = "屍檢台" },
    [17] = { ["object"] = "v_med_cor_cembin", ["price"] = 2000, ["name"] = "垃圾桶 2" },
    [18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 2000, ["name"] = "手推車檯" },
    [19] = { ["object"] = "v_med_cor_chemical", ["price"] = 2000, ["name"] = "化學品" },
    [20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 2000, ["name"] = "BLM 檯" },
    [21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 2000, ["name"] = "文件箱" },
    [22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 2000, ["name"] = "文件櫃" },
    [23] = { ["object"] = "v_med_cor_hose", ["price"] = 2000, ["name"] = "軟管" },
    [24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 2000, ["name"] = "大櫃子" },
    [25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 2000, ["name"] = "燈箱" },
    [26] = { ["object"] = "v_med_cor_medstool", ["price"] = 2000, ["name"] = "醫療工具" },
    [27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 2000, ["name"] = "小冰箱" },
    [28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 2000, ["name"] = "紙巾" },
    [29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 2000, ["name"] = "影印本" },
    [30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 2000, ["name"] = "電視架" },
    [31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 2000, ["name"] = "醫療用品櫃" },
    [32] = { ["object"] = "v_med_examlight", ["price"] = 2000, ["name"] = "燈" },
    [33] = { ["object"] = "v_med_gastank", ["price"] = 2000, ["name"] = "儲氣罐" },
    [34] = { ["object"] = "v_med_hazmatscan", ["price"] = 2000, ["name"] = "危險品掃描器" },
    [35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 2000, ["name"] = "病床頭墻" },
    [36] = { ["object"] = "v_med_hospseating1", ["price"] = 2000, ["name"] = "4人座位凳" },
    [37] = { ["object"] = "v_med_hosptable", ["price"] = 2000, ["name"] = "玻璃台" },
    [38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["name"] = "手提箱" },
    [39] = { ["object"] = "v_med_medwastebin", ["price"] = 2000, ["name"] = "垃圾桶" },
    [40] = { ["object"] = "v_med_oscillator3", ["price"] = 2000, ["name"] = "電子振盪器" },
    [41] = { ["object"] = "prop_ld_health_pack", ["price"] = 1200, ["name"] = "急救包" },
  }
}

lookuptable = {}
dropdowntable = {}
hashtable = {}

for category,v in pairs(furni.objects) do 
  dropdowntable[category] = {}

  for o,k in pairs(v) do

    local hash = GetHashKey(k.object)
    hashtable[hash] = k
  
    local id = k.object or "none"
    local name = k.name or "none"
    local price = k.price or 9999

    lookuptable[id] = k

    table.insert(dropdowntable[category],{id = id,name = name,price = price})
  end 
end 

for k,v in pairs(furni.objects) do
  for k,v in pairs(v) do
    v.id = v.object
  end
end

if not Config.UsingNativeHousing then
  TriggerEvent('esx:getSharedObject', function(obj) ESX = obj; end)
  Citizen.CreateThread(function(...) while not ESX do TriggerEvent('esx:getSharedObject',function(obj) ESX = obj; end); Citizen.Wait(0); end; end)
end

mLibs = exports["meta_libs"]