ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

RegisterServerEvent('esx_extraitems:givebackclip')
AddEventHandler('esx_extraitems:givebackclip', function()
	local _source = source
	local xPlayer = ESX.GetPlayerFromId(_source)
    xPlayer.addInventoryItem('clip', 1)
end)

RegisterServerEvent('esx_extraitems:givebackchips')
AddEventHandler('esx_extraitems:givebackchips', function()
	local _source = source
	local xPlayer = ESX.GetPlayerFromId(_source)
    xPlayer.addInventoryItem('chips', 1)
end)

-- Oxygen Mask
ESX.RegisterUsableItem('oxygen_mask', function(source)
	TriggerClientEvent('esx_extraitems:oxygen_mask', source)
	local xPlayer  = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('oxygen_mask', 1)
    -- TriggerClientEvent('esx_xp:Add', source, 100)
end)

-- Bullet-Proof Vest
ESX.RegisterUsableItem('bulletproof', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('esx_extraitems:bulletproof', source)
    xPlayer.removeInventoryItem('bulletproof', 1)
    -- TriggerClientEvent('esx_xp:Add', source, 50)
end)

-- Bullet-Proof Vest Powerful
ESX.RegisterUsableItem('high_bulletproof', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('esx_extraitems:highbulletproof', source)
    xPlayer.removeInventoryItem('high_bulletproof', 1)
    -- TriggerClientEvent('esx_xp:Add', source, 100)
end)

-- First Aid Kit
-- ESX.RegisterUsableItem('firstaidkit', function(source)
-- 	local xPlayer = ESX.GetPlayerFromId(source)
-- 	TriggerClientEvent('esx_extraitems:firstaidkit', source)
-- 	xPlayer.removeInventoryItem('firstaidkit', 1)
-- end)

-- Weapon Clip
ESX.RegisterUsableItem('clip', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('esx_extraitems:clipcli', source)
    xPlayer.removeInventoryItem('clip', 1)
    TriggerClientEvent('esx_xp:Add', source, 50)
end)

ESX.RegisterUsableItem('chips', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('esx_extraitems:clipclis', source)
    xPlayer.removeInventoryItem('chips', 1)
    TriggerClientEvent('esx_xp:Add', source, 25)
end)


-- WEAPON
ESX.RegisterUsableItem('fireextinguisher_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('fireextinguisher_pack', 1)
    -- xPlayer.addWeapon('WEAPON_FIREEXTINGUISHER',1)
    xPlayer.addInventoryItem('WEAPON_FIREEXTINGUISHER',1)
    TriggerClientEvent('esx_xp:Add', source, 50)
end)

ESX.RegisterUsableItem('knife_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('knife_pack', 1)
    -- xPlayer.addWeapon('WEAPON_KNIFE',1)
    xPlayer.addInventoryItem('WEAPON_KNIFE',1)
    TriggerClientEvent('esx_xp:Add', source, 50)
end)

ESX.RegisterUsableItem('hammer_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('hammer_pack', 1)
    -- xPlayer.addWeapon('WEAPON_HAMMER',1)
    xPlayer.addInventoryItem('WEAPON_HAMMER',1)
    TriggerClientEvent('esx_xp:Add', source, 50)
end)

ESX.RegisterUsableItem('baseballbat_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('baseballbat_pack', 1)
    -- xPlayer.addWeapon('WEAPON_BAT',1)
    xPlayer.addInventoryItem('WEAPON_BAT',1)
    TriggerClientEvent('esx_xp:Add', source, 50)
end)

ESX.RegisterUsableItem('crowbar_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('crowbar_pack', 1)
    -- xPlayer.addWeapon('WEAPON_CROWBAR',1)
    xPlayer.addInventoryItem('WEAPON_CROWBAR',1)
    TriggerClientEvent('esx_xp:Add', source, 50)
end)

ESX.RegisterUsableItem('golfclub_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('golfclub_pack', 1)
    -- xPlayer.addWeapon('WEAPON_GOLFCLUB',1)
    xPlayer.addInventoryItem('WEAPON_GOLFCLUB',1)
    TriggerClientEvent('esx_xp:Add', source, 50)
end)

ESX.RegisterUsableItem('pipewrench_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('pipewrench_pack', 1)
    -- xPlayer.addWeapon('WEAPON_WRENCH',1)
    xPlayer.addInventoryItem('WEAPON_WRENCH',1)
    TriggerClientEvent('esx_xp:Add', source, 50)
end)

ESX.RegisterUsableItem('flashlight_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('flashlight_pack', 1)
    -- xPlayer.addWeapon('WEAPON_FLASHLIGHT',1)
    xPlayer.addInventoryItem('WEAPON_FLASHLIGHT',1)
    TriggerClientEvent('esx_xp:Add', source, 50)
end)

ESX.RegisterUsableItem('hatchet_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('hatchet_pack', 1)
    -- xPlayer.addWeapon('WEAPON_HATCHET',1)
    xPlayer.addInventoryItem('WEAPON_HATCHET',1)
    TriggerClientEvent('esx_xp:Add', source, 50)
end)

ESX.RegisterUsableItem('stungun_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('stungun_pack', 1)
    -- xPlayer.addWeapon('WEAPON_STUNGUN',1)
    xPlayer.addInventoryItem('WEAPON_STUNGUN',1)
    TriggerClientEvent('esx_xp:Add', source, 500)
end)

ESX.RegisterUsableItem('pumpshotgun_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('pumpshotgun_pack', 1)
    -- xPlayer.addWeapon('WEAPON_PUMPSHOTGUN',1)
    xPlayer.addInventoryItem('WEAPON_PUMPSHOTGUN',1)
    TriggerClientEvent('esx_xp:Add', source, 500)
end)

ESX.RegisterUsableItem('snspistol_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('snspistol_pack', 1)
    -- xPlayer.addWeapon('WEAPON_SNSPISTOL',1)
    xPlayer.addInventoryItem('WEAPON_SNSPISTOL',1)
    TriggerClientEvent('esx_xp:Add', source, 500)
end)

ESX.RegisterUsableItem('pistol_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('pistol_pack', 1)
    -- xPlayer.addWeapon('WEAPON_PISTOL',1)
    xPlayer.addInventoryItem('WEAPON_PISTOL',1)
    TriggerClientEvent('esx_xp:Add', source, 500)
end)

ESX.RegisterUsableItem('heavypistol_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('heavypistol_pack', 1)
    -- xPlayer.addWeapon('WEAPON_HEAVYPISTOL',1)
    xPlayer.addInventoryItem('WEAPON_HEAVYPISTOL',1)
    TriggerClientEvent('esx_xp:Add', source, 500)
end)

ESX.RegisterUsableItem('pistol50_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('pistol50_pack', 1)
    -- xPlayer.addWeapon('WEAPON_PISTOL50',1)
    xPlayer.addInventoryItem('WEAPON_PISTOL50',1)
    TriggerClientEvent('esx_xp:Add', source, 500)
end)

ESX.RegisterUsableItem('assaultrifle_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('assaultrifle_pack', 1)
    -- xPlayer.addWeapon('WEAPON_ASSAULTRIFLE',1)
    xPlayer.addInventoryItem('WEAPON_ASSAULTRIFLE',1)
    TriggerClientEvent('esx_xp:Add', source, 1000)
end)

ESX.RegisterUsableItem('carbinerifle_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('carbinerifle_pack', 1)
    -- xPlayer.addWeapon('WEAPON_CARBINERIFLE',1)
    xPlayer.addInventoryItem('WEAPON_CARBINERIFLE',1)
    TriggerClientEvent('esx_xp:Add', source, 1000)
end)

ESX.RegisterUsableItem('sniperrifle_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('sniperrifle_pack', 1)
    -- xPlayer.addWeapon('WEAPON_SNIPERRIFLE',1)
    xPlayer.addInventoryItem('WEAPON_SNIPERRIFLE',1)
    TriggerClientEvent('esx_xp:Add', source, 1000)
end)

ESX.RegisterUsableItem('flaregun_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('flaregun_pack', 1)
    -- xPlayer.addWeapon('WEAPON_FLAREGUN',1)
    xPlayer.addInventoryItem('WEAPON_FLAREGUN',1)
    TriggerClientEvent('esx_xp:Add', source, 1000)
end)

ESX.RegisterUsableItem('nightstick_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('nightstick_pack', 1)
    -- xPlayer.addWeapon('WEAPON_NIGHTSTICK',1)
    xPlayer.addInventoryItem('WEAPON_NIGHTSTICK',1)
    TriggerClientEvent('esx_xp:Add', source, 500)
end)

ESX.RegisterUsableItem('pdw_pack', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('pdw_pack', 1)
    -- xPlayer.addWeapon('WEAPON_NIGHTSTICK',1)
    xPlayer.addInventoryItem('WEAPON_COMBATPDW',1)
    TriggerClientEvent('esx_xp:Add', source, 1000)
end)