-------------------------------------
------- Created by T1GER#9080 -------
------------------------------------- 

Lang = {
  -- CHAT MESSAGES:
  ['dispatch_name']           = '', -- 'Dispatch: '
  ['police_notification1']    = '在 %s | 型號: %s | 車牌: %s | 顏色: %s',
  ['police_notification2']    = '在 %s | 型號: %s | 車牌: %s | 顏色: %s',
  ['alarm_central']           = '警報: ',
  ['vehicle_alarm_triggered'] = '你的 型號: %s [%s] 警報在 %s 響起',

  -- MENU STRINGS:
  ['button_yes']           	  = '是, 價格 $%s',
  ['button_no']           	  = '否',
  ['shop_main_title']         = '選擇載具',
  ['reg_key_title']           = 'Register Key Price: $%s',
  ['reg_alarm_title']         = 'Aquire Alarm Price: $%s',
  ['your_current_keys']       = 'Your Current Keys',
  ['keys_actions_title']      = 'Keys Action [%s]',
  ['give_key_menu']           = '給予車匙',
  ['remove_key_menu']         = '取回車匙',
  ['delete_key_menu']         = '移除車匙',
  ['car_interaction_title']   = 'Car Interaction Menu',
  ['keys_management_label']   = '車匙管理',
  ['veh_windows_label']       = '車窗選項',
  ['veh_door_label']          = '車門選項',
  ['veh_engine_label']        = '引擎開/關',
  ['veh_neon_label']          = '底燈開/關',
  ['insurance_label']         = 'Insured Vehicles',
  ['windows_menu_title']      = 'Windows Up/Down',
  ['window_front_r']       		= '前窗(右)',
  ['window_front_l']       		= '前窗(左)',
  ['window_rear_r']       		= '後窗(右)',
  ['window_rear_l']       		= '後窗(左)',
  ['doors_menu_title']        = 'Open/Close Door',
  ['door_hood']      			    = '引擎蓋',
  ['door_trunk']       			  = '車尾箱',
  ['door_front_l']            = '前門(左)',
  ['door_front_r']            = '前門(右)',
  ['door_rear_l']             = '後門(左)',
  ['door_rear_r']             = '後門(右)',

  -- NOTIFICATIONS:
  ['check_f8_console']        = '~r~CHECK F8 CONSOLE!!!~s~',
  ['not_enough_money']        = '你沒有足夠金錢',
  ['no_players_nearby']       = '附近沒有玩家',
  ['no_veh_nearby']           = '附近沒有載具',
  ['no_owned_vehicles']       = '你沒有擁有任何載具',
  ['engine_not_running']      = '必須開啟引擎',
  ['must_be_inside_veh']      = '必須乘上載具',
  ['must_be_driver_of_veh']   = '你必須在駕駛位置',
  ['veh_must_be_unlocked']    = '必須解鎖載具',
  ['no_veh_in_direction']     = '附近沒有載具',
  ['vehicle_locked']          = '你已鎖上載具',
  ['vehicle_unlocked']        = '你已解鎖載具',
  ['has_key_false']         	= '你沒有這台載具的車匙',
  ['all_veh_has_keys']        = '你沒有註冊任何你的載具',
  ['key_reg_accepted']        = '你已成功註冊車匙',
  ['all_veh_have_alarm']      = '你已為你所有載具安裝警報',
  ['alarm_aquired']           = '你已成功安裝警報',
  ['no_registerd_keys']       = '你沒有任何已註冊的車匙',
  ['keys_received1']          = '你已收到 [%s] 的車匙',
  ['keys_received2']          = '你已從%s收到 [%s] 車匙',
  ['u_gave_keys']             = '你已給予 [%s] 至 %s',
  ['u_removed_a_key']         = '你已從 %s 取回 [%s] 的車匙',
  ['u_had_a_key_removed']     = '你的車匙 [%s] 已被 %s 收回',
  ['target_has_no_key_copy']  = '%s 沒有這條車匙...',
  ['couldnt_find_keys']       = '沒有找到 [%s]',
  ['keys_deleted']            = '已丟棄 %s [%s] 的車匙',
  ['engine_toggled_on']       = '已開啟引擎',
  ['engine_toggled_off']      = '已關閉引擎',
  ['npc_ran_away']      		  = '他連車匙也拿走了',
  ['already_lockpicking']     = '你正在解鎖載具',
  ['move_closer_to_lockpick'] = '請走近載具',
  ['cant_lockpick_ems']       = '不能解鎖緊急載具',
  ['first_check_if_locked']   = '請檢查車輛是否鎖住了...',
  ['deny_lockpick_unlocked']  = '無法解鎖未鎖上的載具',
  ['veh_lockpicked_success']  = '你已成功解鎖載具，請',
  ['veh_lockpicked_fail']     = '你未能成功解鎖載具',
  ['deny_hotwire']            = '無必要電線短路載具',
  ['hotwire_the_vehicle']     = '嘗試電線短路載具以開啟引擎',
  ['already_hotwiring']       = '你已正在進行電線短路',
  ['veh_hotwire_success']     = '你成功短路載具',
  ['veh_hotwire_fail']        = '你未能成功短路載具',
  ['already_searching']       = 'You are already searching a vehicle!',
  ['stop_the_vehicle']        = 'Please stop the vehicle first!',
  ['cannot_search_car']       = 'This car is empty, dont even bother!',
  ['cash_found_x']      		  = 'You found ~g~$%s~s~ in cash.',
  ['item_found_x']      			= 'You found ~b~%sx~s~ ~y~%s~s~.',

  -- DRAW TEXTS:
  ['draw_locksmith']          = '~r~[E]~s~ Lock Smith',
  ['draw_alarmshop']          = '~r~[E]~s~ 載具警報商店',

  -- PROGRESSBARS:
  ['progbar_talking']         = '與NPC談話中',
  ['progbar_searching']       = '搜索中',
  ['progbar_hotwiring']       = '正在嘗試電線短路',
  ['progbar_lockpicking']     = '正在嘗試解鎖',
  
  -- BLIPS:
  ['blip_locksmith']          = 'Locksmith',
  ['blip_alarmshop']          = '載具警報商店',
}
