maxVehiclePerformanceUpgrades = 0 -- Set to 0 to have all the upgrades
vehicleBaseRepairCost = 3000
vehicleRepairCostMultiplier = 1
moneyType = 'bank'

-- Location Configs
-- Add locations here
-- Add jobs specific to the garage.
bennyGarages = {
    [1] = {
        coords = vector4(-211.55, -1324.55, 30.90, 319.73135375977),
        using = false,
        blips = true,
        useJob = true,
        job = {["mechanic"] = 1}
    },
    -- [2] = {coords = vector4(144.9972, -3030.3623, 6.7192, 180.1276), using = false, blips = false,  useJob = true, job = {["mechanic"] = 1}},
    -- [3] = {coords = vector4(135.8779, -3030.6948, 7.0421, 12.7910), using = false, blips = false,  useJob = true, job = {["mechanic"] = 1}},
    -- [4] = {coords = vector4(124.3727, -3041.3113, 7.0409, 271.4666), using = false, blips = false,  useJob = true, job = {["mechanic"] = 1}},
    -- [5] = {coords = vector4(136.07, -3042.65, 7.04, 359.2), using = false, blips = false,  useJob = true, job = {["mechanic"] = 1}},
    -- [6] = {coords = vector4(144.94, -3043.9, 7.04, 0.94), using = false, blips = false,  useJob = true, job = {["mechanic"] = 1}},
    [2] = {
        coords = vector4(-690.55, -788.29, 26.02, 179.62),
        using = false,
        blips = false,
        useJob = true,
        job = {["mechanic"] = 1}
    },
    [3] = {
        coords = vector4(-695.63, -788.39, 26.02, 179.62),
        using = false,
        blips = false,
        useJob = true,
        job = {["mechanic"] = 1}
    },
    [4] = {
        coords = vector4(-700.93, -788.31, 26.02, 182.95),
        using = false,
        blips = false,
        useJob = true,
        job = {["mechanic"] = 1}
    },
    [5] = {
        coords = vector4(-675.89, -772.91, 26.19, 268.09),
        using = false,
        blips = false,
        useJob = true,
        job = {["mechanic"] = 1}
    },
    [6] = {
        coords = vector4(-676.04, -784.08, 26.19, 269.57),
        using = false,
        blips = false,
        useJob = true,
        job = {["mechanic"] = 1}
    }
    -- [99] = {coords = vector4(2560.45, 3010.05, 20.83, 322.14), blips = false,  useJob = false, job = {}},
}

--[[ bennyLocations = {
    vector4(-211.55, -1324.55, 30.90, 319.731)
} ]]

-- ADJUST PRICING

vehicleCustomisationPrices = {
    horns = {price = 1.2},
    cosmetics = {price = 1.4},
    respray = {price = 1.3},
    performance = {prices = {0, 1.1, 1.7, 2.6, 3.05, 3.40}},
    -- 0 = default, 1 = level 1, 2 = level 2, 3 = level 3, 4 = level 4, 5 = level 5
    turbo = {price = 2},
    wheels = {price = 1.4},
    customwheels = {price = 1.7},
    wheelsmoke = {price = 1.5},
    windowtint = {price = 1.3},
    neonside = {price = 1.3},
    neoncolours = {price = 1.6},
    headlights = {price = 1.3},
    xenoncolours = {price = 1.6},
    oldlivery = {price = 0.0},
    plateindex = {price = 1.4}
}

-- RESPRAY CATEGORIES

vehicleResprayCategories = {
    {category = "主色調", id = 0},
    {category = "副色調", id = 1},
    {category = "鉻合金", id = 2},
    {category = "車輪色調", id = 3},
    {category = "內裝色調", id = 4},
    {category = "儀表版色調", id = 5}
}

-- WINDOW TINTS

vehicleWindowTintOptions = {
    {name = "原裝", id = 4},
    {name = "透明玻璃", id = 0},
    {name = "純黑色", id = 1},
    {name = "黑煙", id = 2},
    {name = "輕型黑煙", id = 3},
    {name = "綠色", id = 5}
}

-- HEADLIGHTS

vehicleXenonOptions = {
    xenonColours = {
        {name = "原裝", id = 255},
        {name = "白色", id = 0},
        {name = "藍色", id = 1},
        {name = "電子藍", id = 2},
        {name = "薄荷綠", id = 3},
        {name = "青檸檬綠", id = 4},
        {name = "黃色", id = 5},
        {name = "黃金雨", id = 6},
        {name = "橘色", id = 7},
        {name = "紅色", id = 8},
        {name = "小馬粉", id = 9},
        {name = "熱情粉紅", id = 10},
        {name = "紫色", id = 11},
        {name = "黑光", id = 12}
    }
}

-- WHEELS

vehicleWheelOptions = {
    {category = "客製化車肽", id = -1, wheelID = 23},
    {category = "燒胎煙霧", id = 20, wheelID = 23},
    {category = "跑車", id = 0, wheelID = 23},
    {category = "美式肌肉車", id = 1, wheelID = 23},
    {category = "低底盤車", id = 2, wheelID = 23},
    {category = "運動休旅車", id = 3, wheelID = 23},
    {category = "越野車", id = 4, wheelID = 23},
    {category = "改裝車", id = 5, wheelID = 23},
    {category = "電單車", id = 6, wheelID = 23},
    {category = "高檔車", id = 7, wheelID = 23},
    {category = "DLC", id = 8, wheelID = 23},
    {category = "自訂車鈴", id = 0, wheelID = 23}
}

-- TIRE SMOKE

vehicleTyreSmokeOptions = {
    {name = "白色燒胎煙霧", r = 254, g = 254, b = 254},
    {name = "黑色燒胎煙霧", r = 1, g = 1, b = 1},
    {name = "藍色燒胎煙霧", r = 0, g = 150, b = 255},
    {name = "黃色燒胎煙霧", r = 255, g = 255, b = 50},
    {name = "橘色燒胎煙霧", r = 255, g = 153, b = 51},
    {name = "紅色燒胎煙霧", r = 255, g = 10, b = 10},
    {name = "綠色燒胎煙霧", r = 10, g = 255, b = 10},
    {name = "紫色燒胎煙霧", r = 153, g = 10, b = 153},
    {name = "粉紅色燒胎煙霧", r = 255, g = 102, b = 178},
    {name = "灰色燒胎煙霧", r = 128, g = 128, b = 128}
}

-- NEONS

vehicleNeonOptions = {
    category = "Neons",
    neonTypes = {
        {name = "前置霓虹", id = 2},
        {name = "後置霓虹", id = 3},
        {name = "左邊霓虹", id = 0},
        {name = "右邊霓虹", id = 1}
    },
    neonColours = {
        {name = "白色", r = 222, g = 222, b = 255},
        {name = "藍色", r = 2, g = 21, b = 255},
        {name = "電子藍", r = 3, g = 83, b = 255},
        {name = "薄荷綠", r = 0, g = 255, b = 140},
        {name = "青檸檬綠", r = 94, g = 255, b = 1},
        {name = "黃色", r = 255, g = 255, b = 0},
        {name = "黃金雨", r = 255, g = 150, b = 0},
        {name = "橘色", r = 255, g = 62, b = 0},
        {name = "紅色", r = 255, g = 1, b = 1},
        {name = "小馬粉", r = 255, g = 50, b = 100},
        {name = "熱情粉紅", r = 255, g = 5, b = 190},
        {name = "紫色", r = 35, g = 1, b = 255},
        {name = "黑光", r = 15, g = 3, b = 255}
    }
}

-- MAIN COMPONENTS

vehicleCustomisation = {
    {category = "擾流板", id = 0},
    {category = "前保險桿", id = 1},
    {category = "後保險桿", id = 2},
    {category = "側裙", id = 3},
    {category = "排氣管", id = 4},
    {category = "防滾架", id = 5},
    {category = "水箱護罩", id = 6},
    {category = "引擎蓋", id = 7},
    {category = "左擋泥板", id = 8},
    {category = "右擋泥板", id = 9},
    {category = "車頂", id = 10},
    {category = "引擎升級", id = 11},
    {category = "剎車升級", id = 12},
    {category = "變速箱升級", id = 13},
    {category = "懸掛升級", id = 15},
    {category = "裝甲升級", id = 16},
    {category = "渦輪升級", id = 18},
    {category = "車牌 - 前面", id = 25},
    {category = "車牌 - 後面", id = 26},
    {category = "Trim A", id = 27},
    {category = "裝飾品", id = 28},
    {category = "儀表版", id = 29},
    {category = "錶盤", id = 30},
    {category = "車門音箱", id = 31},
    {category = "座椅", id = 32},
    {category = "方向盤", id = 33},
    {category = "換擋器", id = 34},
    {category = "牌匾", id = 35},
    {category = "音箱", id = 36},
    {category = "車尾箱", id = 37},
    {category = "液壓系統", id = 38},
    {category = "引擎殼體", id = 39},
    {category = "引擎空氣過濾器", id = 40},
    {category = "撐桿", id = 41},
    {category = "車輪拱罩", id = 42},
    {category = "天線", id = 43},
    {category = "Trim B", id = 44},
    {category = "油箱", id = 45},
    {category = "擋風玻璃", id = 46},
    {category = "塗裝", id = 48},
    {category = "Light Bar", id = 49},
    {
        category = "喇叭",
        id = 14,

        hornNames = {
            {name = "貨車 Horn", id = 0},
            {name = "警車 Horn", id = 1},
            {name = "小丑花車 Horn", id = 2},
            {name = "音樂 Horn 1", id = 3},
            {name = "音樂 Horn 2", id = 4},
            {name = "音樂 Horn 3", id = 5},
            {name = "音樂 Horn 4", id = 6},
            {name = "音樂 Horn 5", id = 7},
            {name = "悲傷長號", id = 8},
            {name = "古典 Horn 1", id = 9},
            {name = "古典 Horn 2", id = 10},
            {name = "古典 Horn 3", id = 11},
            {name = "古典 Horn 4", id = 12},
            {name = "古典 Horn 5", id = 13},
            {name = "古典 Horn 6", id = 14},
            {name = "古典 Horn 7", id = 15},
            {name = "音階 - Do", id = 16},
            {name = "音階 - Re", id = 17},
            {name = "音階 - Mi", id = 18},
            {name = "音階 - Fa", id = 19},
            {name = "音階 - Sol", id = 20},
            {name = "音階 - La", id = 21},
            {name = "音階 - Ti", id = 22},
            {name = "音階 - Do", id = 23},
            {name = "爵士 Horn 1", id = 24},
            {name = "爵士 Horn 2", id = 25},
            {name = "爵士 Horn 3", id = 26},
            {name = "爵士 Horn Loop", id = 27},
            {name = "星條旗 1", id = 28},
            {name = "星條旗 2", id = 29},
            {name = "星條旗 3", id = 30},
            {name = "星條旗 4", id = 31},
            {name = "古典循環喇叭 8", id = 32},
            {name = "古典循環喇叭 9", id = 33},
            {name = "古典循環喇叭 10", id = 34},
            {name = "古典喇叭 8", id = 35},
            {name = "古典喇叭 9", id = 36},
            {name = "古典喇叭 10", id = 37},
            {name = "萬聖節循環喇叭 1", id = 38},
            {name = "萬聖節喇叭 1", id = 39},
            {name = "萬聖節循環喇叭 2", id = 40},
            {name = "萬聖節喇叭 2", id = 41},
            {name = "聖安地列斯循環", id = 42},
            {name = "聖安地列斯", id = 43},
            {name = "自由市循環", id = 44},
            {name = "自由市", id = 45},
            {name = "節慶循環喇叭 1", id = 46},
            {name = "節慶喇叭 1", id = 47},
            {name = "節慶循環喇叭 2", id = 48},
            {name = "節慶喇叭 2", id = 49},
            {name = "節慶循環喇叭 3", id = 50},
            {name = "節慶喇叭 3", id = 51},
            {name = "喇叭 #1", id = 52},
            {name = "喇叭 #2", id = 53},
            {name = "喇叭 #3", id = 54},
            {name = "喇叭 #4", id = 55},
            {name = "喇叭 #5", id = 56},
            {name = "喇叭 #6", id = 57},
            {name = "喇叭 #7", id = 58},
            {name = "喇叭 #8", id = 59},
            {name = "喇叭 #9", id = 60}
        }
    }
}

-- COLORS

vehicleResprayOptions = {
    {category = "經典", id = 0,
        colours = {
            {name = "黑色", id = 0},
            {name = "墨黑色", id = 1},
            {name = "精鋼黑", id = 2},
            {name = "闇鋼黑", id = 3},
            {name = "無菸煤黑", id = 11},
            { id = 12, name = '啞光黑色'},
            { id = 15, name = '黑夜'},
            { id = 16, name = '深黑色'},
            { id = 21, name = '石油'},
            {name = "碳黑色", id = 147},

            {name = "銀白", id = 4},
            {name = "銀藍", id = 5},
            {name = "白鋼", id = 6},
            {name = "暗影銀", id = 7},
            {name = "銀灰色", id = 8},
            {name = "午夜銀", id = 9},
            {name = "鑄鐵銀", id = 10},
            { id = 13, name = '灰色墊子'},
            { id = 14, name = '淺灰色'},
            { id = 17, name = '瀝青灰色'},
            { id = 18, name = '混凝土灰色'},
            { id = 19, name = '黑銀'},
            { id = 20, name = '菱鎂礦'},
            { id = 22, name = '鎳'},
            { id = 23, name = '鋅'},
            { id = 24, name = '白雲石'},
            { id = 25, name = '藍銀'},
            { id = 26, name = '鈦'},
            {name = "海洋藍", id = 66},
            { id = 93, name = '香檳酒'},
            { id = 144, name = '灰色獵人'},
            { id = 156, name = '灰色'},

            {name = "紅色", id = 27},
            {name = "深磚紅", id = 28},
            {name = "大紅色", id = 29},
            {name = "烈焰紅", id = 30},
            {name = "優雅深紅", id = 31},
            {name = "石榴紅", id = 32},
            {name = "日落橘紅", id = 33},
            {name = "赤霞珠紅", id = 34},
            {name = "葡萄紫紅", id = 35},
            { id = 39, name = '啞光紅色'},
            { id = 40, name = '深紅'},
            { id = 43, name = '紅色漿'},
            { id = 44, name = '燦爛的紅色'},
            { id = 46, name = '淡紅色'},
            {name = "酒紅", id = 143},
            {name = "火山橘紅", id = 150},

            {name = "熱情粉紅", id = 135},
            {name = "鮭魚粉橘", id = 136},
            {name = "菲斯特粉紅", id = 137},

            {name = "日出橘", id = 36},
            {name = "橘色", id = 38},
            { id = 41, name = '啞光橙色'},
            { id = 123, name = '淡橙色'},
            { id = 124, name = '桃子'},
            { id = 130, name = '南瓜'},
            {name = "亮橘色", id = 138},

            { id = 45, name = '銅'},
            { id = 47, name = '淺褐色'},
            { id = 48, name = '深棕色'},
            {name = "青銅色", id = 90},
            {name = "飛特者棕", id = 94},
            {name = "黃棕色", id = 95},
            {name = "巧克力棕", id = 96},
            {name = "栗棕色", id = 97},
            {name = "正棕色", id = 98},
            {name = "淺黃棕", id = 99},
            {name = "苔蘚棕", id = 100},
            {name = "褐棕色", id = 101},
            {name = "木棕色", id = 102},
            {name = "暖棕色", id = 103},
            {name = "褐色", id = 104},
            {name = "沙棕色", id = 105},
            { id = 108, name = '棕色'},
            { id = 109, name = '榛子'},
            { id = 110, name = '貝殼'},
            { id = 114, name = '桃花心木'},
            { id = 115, name = '釜'},
            { id = 116, name = '金發'},
            { id = 129, name = '礫石'},
            { id = 153, name = '黑暗的地球'},
            { id = 154, name = '沙漠'},

            {name = "黃色", id = 88},
            {name = "賽車黃", id = 89},
            {name = "正黃色", id = 91},
            {name = "深綠色", id = 49},
            {name = "賽車綠", id = 50},
            {name = "水青玉色", id = 51},
            {name = "橄欖綠", id = 52},
            {name = "亮綠色", id = 53},
            {name = "汽油綠", id = 54},
            { id = 55, name = '青檸檬綠'},
            { id = 56, name = '森林綠'},
            { id = 57, name = '草坪綠'},
            { id = 58, name = '皇家綠'},
            { id = 59, name = '綠色瓶'},
            {name = "青檸檬綠", id = 92},
            {name = "闇夜藍", id = 141},
            {name = "銀河藍", id = 61},
            {name = "深藍色", id = 62},
            {name = "薩克森藍", id = 63},
            {name = "藍色", id = 64},
            {name = "水手藍", id = 65},
            {name = "寶鑽藍", id = 67},
            {name = "浪花藍", id = 68},
            {name = "深海藍", id = 69},
            {name = "賽車藍", id = 73},
            {name = "極致藍", id = 70},
            {name = "淺藍色", id = 74},
            { id = 75, name = '藍夜'},
            { id = 77, name = '青色藍色'},
            { id = 78, name = '鈷'},
            { id = 79, name = '電藍色'},
            { id = 80, name = '地平線藍色'},
            { id = 82, name = '金屬藍色'},
            { id = 83, name = '藍晶'},
            { id = 84, name = '藍瑪瑙'},
            { id = 85, name = '鋯'},
            { id = 86, name = '尖晶石'},
            { id = 87, name = '電氣石'},

            { id = 60, name = '淺藍'},
            { id = 127, name = '藍天堂'},
            { id = 140, name = '泡泡糖'},
            { id = 146, name = '禁止藍色'},
            { id = 157, name = '冰川藍'},
            { id = 42, name = '黃色'},
            { id = 126, name = '淺黃色'},
            { id = 125, name = '綠色阿尼斯'},
            { id = 128, name = '黃褐色'},
            { id = 133, name = '軍綠色'},
            { id = 151, name = '深綠色'},
            { id = 152, name = '獵人綠'},
            { id = 155, name = '啞光葉子綠色'},

            {name = "莎夫特紫", id = 71},
            {name = "亮紫紅", id = 72},
            { id = 76, name = '暗紫羅蘭'},
            { id = 81, name = '紫晶'},
            {name = "午夜紫", id = 142},
            {name = "亮紫色", id = 145},
            { id = 148, name = '神秘的紫羅蘭'},
            { id = 149, name = '啞光深紫色'},

            { id = 37, name = '金色'},
            { index = 158, name = '純金'},
            { index = 159, name = '拉絲金'},
            { id = 160, name = '輕金'},

            {name = "洗白棕", id = 106},
            {name = "奶油色", id = 107},
            {name = "冰晶白", id = 111},
            {name = "蒼霜白", id = 112},
            { id = 113, name = '米色'},
            { id = 121, name = '啞光白色'},
            { id = 122, name = '雪'},
            { id = 131, name = '棉花'},
            { id = 132, name = '雪花'},
            { id = 134, name = '純白'},
        }
    },
    {category = "亮金屬", id = 1,
        colours = {
            {name = "黑色", id = 0},
            {name = "墨黑色", id = 1},
            {name = "精鋼黑", id = 2},
            {name = "闇鋼黑", id = 3},
            {name = "無菸煤黑", id = 11},
            { id = 12, name = '啞光黑色'},
            { id = 15, name = '黑夜'},
            { id = 16, name = '深黑色'},
            { id = 21, name = '石油'},
            {name = "碳黑色", id = 147},

            {name = "銀白", id = 4},
            {name = "銀藍", id = 5},
            {name = "白鋼", id = 6},
            {name = "暗影銀", id = 7},
            {name = "銀灰色", id = 8},
            {name = "午夜銀", id = 9},
            {name = "鑄鐵銀", id = 10},
            { id = 13, name = '灰色墊子'},
            { id = 14, name = '淺灰色'},
            { id = 17, name = '瀝青灰色'},
            { id = 18, name = '混凝土灰色'},
            { id = 19, name = '黑銀'},
            { id = 20, name = '菱鎂礦'},
            { id = 22, name = '鎳'},
            { id = 23, name = '鋅'},
            { id = 24, name = '白雲石'},
            { id = 25, name = '藍銀'},
            { id = 26, name = '鈦'},
            {name = "海洋藍", id = 66},
            { id = 93, name = '香檳酒'},
            { id = 144, name = '灰色獵人'},
            { id = 156, name = '灰色'},

            {name = "紅色", id = 27},
            {name = "深磚紅", id = 28},
            {name = "大紅色", id = 29},
            {name = "烈焰紅", id = 30},
            {name = "優雅深紅", id = 31},
            {name = "石榴紅", id = 32},
            {name = "日落橘紅", id = 33},
            {name = "赤霞珠紅", id = 34},
            {name = "葡萄紫紅", id = 35},
            { id = 39, name = '啞光紅色'},
            { id = 40, name = '深紅'},
            { id = 43, name = '紅色漿'},
            { id = 44, name = '燦爛的紅色'},
            { id = 46, name = '淡紅色'},
            {name = "酒紅", id = 143},
            {name = "火山橘紅", id = 150},

            {name = "熱情粉紅", id = 135},
            {name = "鮭魚粉橘", id = 136},
            {name = "菲斯特粉紅", id = 137},

            {name = "日出橘", id = 36},
            {name = "橘色", id = 38},
            { id = 41, name = '啞光橙色'},
            { id = 123, name = '淡橙色'},
            { id = 124, name = '桃子'},
            { id = 130, name = '南瓜'},
            {name = "亮橘色", id = 138},

            { id = 45, name = '銅'},
            { id = 47, name = '淺褐色'},
            { id = 48, name = '深棕色'},
            {name = "青銅色", id = 90},
            {name = "飛特者棕", id = 94},
            {name = "黃棕色", id = 95},
            {name = "巧克力棕", id = 96},
            {name = "栗棕色", id = 97},
            {name = "正棕色", id = 98},
            {name = "淺黃棕", id = 99},
            {name = "苔蘚棕", id = 100},
            {name = "褐棕色", id = 101},
            {name = "木棕色", id = 102},
            {name = "暖棕色", id = 103},
            {name = "褐色", id = 104},
            {name = "沙棕色", id = 105},
            { id = 108, name = '棕色'},
            { id = 109, name = '榛子'},
            { id = 110, name = '貝殼'},
            { id = 114, name = '桃花心木'},
            { id = 115, name = '釜'},
            { id = 116, name = '金發'},
            { id = 129, name = '礫石'},
            { id = 153, name = '黑暗的地球'},
            { id = 154, name = '沙漠'},

            {name = "黃色", id = 88},
            {name = "賽車黃", id = 89},
            {name = "正黃色", id = 91},
            {name = "深綠色", id = 49},
            {name = "賽車綠", id = 50},
            {name = "水青玉色", id = 51},
            {name = "橄欖綠", id = 52},
            {name = "亮綠色", id = 53},
            {name = "汽油綠", id = 54},
            { id = 55, name = '青檸檬綠'},
            { id = 56, name = '森林綠'},
            { id = 57, name = '草坪綠'},
            { id = 58, name = '皇家綠'},
            { id = 59, name = '綠色瓶'},
            {name = "青檸檬綠", id = 92},
            {name = "闇夜藍", id = 141},
            {name = "銀河藍", id = 61},
            {name = "深藍色", id = 62},
            {name = "薩克森藍", id = 63},
            {name = "藍色", id = 64},
            {name = "水手藍", id = 65},
            {name = "寶鑽藍", id = 67},
            {name = "浪花藍", id = 68},
            {name = "深海藍", id = 69},
            {name = "賽車藍", id = 73},
            {name = "極致藍", id = 70},
            {name = "淺藍色", id = 74},
            { id = 75, name = '藍夜'},
            { id = 77, name = '青色藍色'},
            { id = 78, name = '鈷'},
            { id = 79, name = '電藍色'},
            { id = 80, name = '地平線藍色'},
            { id = 82, name = '金屬藍色'},
            { id = 83, name = '藍晶'},
            { id = 84, name = '藍瑪瑙'},
            { id = 85, name = '鋯'},
            { id = 86, name = '尖晶石'},
            { id = 87, name = '電氣石'},

            { id = 60, name = '淺藍'},
            { id = 127, name = '藍天堂'},
            { id = 140, name = '泡泡糖'},
            { id = 146, name = '禁止藍色'},
            { id = 157, name = '冰川藍'},
            { id = 42, name = '黃色'},
            { id = 126, name = '淺黃色'},
            { id = 125, name = '綠色阿尼斯'},
            { id = 128, name = '黃褐色'},
            { id = 133, name = '軍綠色'},
            { id = 151, name = '深綠色'},
            { id = 152, name = '獵人綠'},
            { id = 155, name = '啞光葉子綠色'},

            {name = "莎夫特紫", id = 71},
            {name = "亮紫紅", id = 72},
            { id = 76, name = '暗紫羅蘭'},
            { id = 81, name = '紫晶'},
            {name = "午夜紫", id = 142},
            {name = "亮紫色", id = 145},
            { id = 148, name = '神秘的紫羅蘭'},
            { id = 149, name = '啞光深紫色'},

            { id = 37, name = '金色'},
            { index = 158, name = '純金'},
            { index = 159, name = '拉絲金'},
            { id = 160, name = '輕金'},

            {name = "洗白棕", id = 106},
            {name = "奶油色", id = 107},
            {name = "冰晶白", id = 111},
            {name = "蒼霜白", id = 112},
            { id = 113, name = '米色'},
            { id = 121, name = '啞光白色'},
            { id = 122, name = '雪'},
            { id = 131, name = '棉花'},
            { id = 132, name = '雪花'},
            { id = 134, name = '純白'},
        }
    },
    {category = "霧面", id = 2,
        colours = {
            {name = "黑色", id = 12},
            {name = "灰色", id = 13},
            {name = "淺灰色", id = 14},
            {name = "冰晶白", id = 131},
            {name = "藍色", id = 83},
            {name = "深藍色", id = 82},
            {name = "闇夜藍", id = 84},
            {name = "午夜紫", id = 149},
            {name = "莎夫特紫", id = 148},
            {name = "紅色", id = 39},
            {name = "深紅色", id = 40},
            {name = "橘色", id = 41},
            {name = "黃色", id = 42},
            {name = "青檸檬綠", id = 55},
            {name = "綠色", id = 128},
            {name = "森林綠", id = 151},
            {name = "葉綠色", id = 155},
            {name = "橄欖褐", id = 152},
            {name = "深泥色", id = 153},
            {name = "黃沙色", id = 154}
        }
    },
    {category = "金屬", id = 3,
        colours = {
            {name = "髮絲鋼", id = 117},
            {name = "髮絲黑鋼", id = 118},
            {name = "髮絲鋁", id = 119},
            {name = "純金色", id = 158},
            {name = "髮絲金", id = 159},
            {name = "鉻合金", id = 120}
        }
    }
}