firetruk = {
    model = `firetruk`,
    name = "Fire Truck",
    controlToOperate = {73, "INPUT_VEH_DUCK"},
    pedAttachment = {
        id = "LadderSeat",
        offSet = {-0.91, -1.89, 0.63},
        rotation = {0.0, 0.0, 0.0},
    },
    drawRotation = false,
    animation = {
        enabled = true,
        idle = {
            dict = "anim@arena@amb@seating@seat_b@",
            name = "base"
        },
        
    },
    cage = {
        enabled = true,
        id = "Cage",
        offSet = {0.0, 0.5, 1.05},
        rotation = {0.0, 0.0, 0.0},
    },
    data = {
        {
            id = "LadderSeat",
            model = `ladder_seat`,
            isLadder = false,
            attachTo = "vehicle",
            boneIndex = "", -- If attaching to vehicle
            defaultOffSet = {0.0, -1.59, 0.52},
            offSet = {0.0, -1.59, 0.52},
            rotation = {0.0, 0.0, 0.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = false,
            minimumOffSet = {0.0, 0.0, 0.0},
            maxOffSet = false,
            maximumOffSet = {0.0, 0.0, 0.0},
            controls = {
                [63] = {
                    movementType = "rotate",
                    axis = 3,
                    movementAmount = 0.1,
                },
                [64] = {
                    movementType = "rotate",
                    axis = 3,
                    movementAmount = -0.1,
                },
            }
        },
        {
            id = "LadderBottom",
            model = `ladder_base`,
            isLadder = false,
            attachTo = "LadderSeat",
            defaultOffSet = {0.0, -2.0, 1.17},
            offSet = {0.0, -2.0, 1.17},
            rotation = {0.0, 0.0, 0.0},
            minRotation = true,
            minimumRotation = {-1.0, 0.0, 0.0},
            maxRotation = true,
            maximumRotation = {84.5, 0.0, 0.0},
            minOffSet = false,
            minimumOffSet = {0.0, 0.0, 0.0},
            maxOffSet = false,
            maximumOffSet = {0.0, 0.0, 0.0},
            controls = {
                [136] = {
                    movementType = "rotate",
                    axis = 1,
                    movementAmount = 0.1,
                },
                [130] = {
                    movementType = "rotate",
                    axis = 1,
                    movementAmount = -0.1,
                },
            }
        },
        {
            id = "OuterLadder",
            model = `ladder_outer`,
            isLadder = true,
            attachTo = "LadderBottom",
            defaultOffSet = {0.0, 2.69, 0.0},
            offSet = {0.0, 2.69, 0.0},
            rotation = {0.0, 0.0, 0.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = true,
            minimumOffSet = {0.0, 2.69, 0.0},
            maxOffSet = true,
            maximumOffSet = {0.0, 8.3801, 0.0},
            controls = {
                [131] = {
                    movementType = "move",
                    axis = 2,
                    movementAmount = 0.01,
                },
                [132] = {
                    movementType = "move",
                    axis = 2,
                    movementAmount = -0.01,
                },
            }
        },
        {
            id = "MiddleLadder",
            model = `ladder_middle`,
            isLadder = true,
            attachTo = "OuterLadder",
            defaultOffSet = {0.0, 0.1, 0.3},
            offSet = {0.0, 0.1, 0.3},
            rotation = {0.0, 0.0, 0.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = true,
            minimumOffSet = {0.0, 0.1, 0.3},
            maxOffSet = true,
            maximumOffSet = {0.0, 5.71, 0.0},
            controls = {
                [131] = {
                    movementType = "move",
                    axis = 2,
                    movementAmount = 0.01,
                },
                [132] = {
                    movementType = "move",
                    axis = 2,
                    movementAmount = -0.01,
                },
            }
        },
        {
            id = "InnerLadder",
            model = `ladder_inner`,
            isLadder = true,
            attachTo = "MiddleLadder",
            defaultOffSet = {0.0, 0.6, -0.16},
            offSet = {0.0, 0.6, -0.16},
            rotation = {0.0, 0.0, 0.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = true,
            minimumOffSet = {0.0, 0.6, -0.16},
            maxOffSet = true,
            maximumOffSet = {0.0, 5.69, -0.16},
            controls = {
                [131] = {
                    movementType = "move",
                    axis = 2,
                    movementAmount = 0.01,
                },
                [132] = {
                    movementType = "move",
                    axis = 2,
                    movementAmount = -0.01,
                },
            }
        },
        {
            id = "RotatingEnd",
            model = `ladder_end_piece`,
            isLadder = false,
            attachTo = "InnerLadder",
            defaultOffSet = {0.0, 3.1860, 0.0490},
            offSet = {0.0, 3.1860, 0.0490},
            rotation = {0.0, 0.0, 0.0},
            minRotation = true,
            minimumRotation = {-29.4, 0.0, 0.0},
            maxRotation = true,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = false,
            minimumOffSet = {0.0, 0.0, 0.0},
            maxOffSet = false,
            maximumOffSet = {0.0, 0.0, 0.0},
            controls = {
                [172] = {
                    movementType = "rotate",
                    axis = 1,
                    movementAmount = 0.2,
                },
                [173] = {
                    movementType = "rotate",
                    axis = 1,
                    movementAmount = -0.2,
                },
            }
        },
        {
            id = "Cage",
            model = `ladder_cage`,
            isLadder = false,
            attachTo = "RotatingEnd",
            defaultOffSet = {0.0, 2.72, -0.3030},
            offSet = {0.0, 2.72, -0.3030},
            rotation = {90.3321, 0.0, 0.0},
            minRotation = true,
            minimumRotation = {-102.6667, 0.0, 0.0},
            maxRotation = true,
            maximumRotation = {90.3321, 0.0, 0.0},
            minOffSet = false,
            minimumOffSet = {0.0, 0.0, 0.0},
            maxOffSet = false,
            maximumOffSet = {0.0, 0.0, 0.0},
            controls = {
                [174] = {
                    movementType = "rotate",
                    axis = 1,
                    movementAmount = 0.2,
                },
                [175] = {
                    movementType = "rotate",
                    axis = 1,
                    movementAmount = -0.2,
                },
            }
        },
        {
            id = "OutRigger1",
            model = `outrigger`,
            isLadder = false,
            attachTo = "vehicle",
            defaultOffSet = {-0.1540, 1.1250, 0.1330},
            offSet = {-0.1540, 1.1250, 0.1330},
            rotation = {0.0, 0.0, 0.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = true,
            minimumOffSet = {-1.3440, 1.1250, 0.1330},
            maxOffSet = true,
            maximumOffSet = {-0.1540, 0.0, 0.0},
            controls = {
                [208] = {
                    movementType = "move",
                    axis = 1,
                    movementAmount = -0.005,
                },
                [207] = {
                    movementType = "move",
                    axis = 1,
                    movementAmount = 0.005,
                },
            }
        },
        {
            id = "OutRigger2",
            model = `outrigger`,
            isLadder = false,
            attachTo = "vehicle",
            defaultOffSet = {-0.1540, -3.4020, 0.1330},
            offSet = {-0.1540, -3.4020, 0.1330},
            rotation = {0.0, 0.0, 0.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = true,
            minimumOffSet = {-1.3440, -3.4020, 0.1330},
            maxOffSet = true,
            maximumOffSet = {-0.1540, 0.0, 0.0},
            controls = {
                [208] = {
                    movementType = "move",
                    axis = 1,
                    movementAmount = -0.005,
                },
                [207] = {
                    movementType = "move",
                    axis = 1,
                    movementAmount = 0.005,
                },
            }
        },
        {
            id = "OutRigger3",
            model = `outrigger`,
            isLadder = false,
            attachTo = "vehicle",
            defaultOffSet = {0.1740, 0.9340, 0.1330},
            offSet = {0.1740, 0.9340, 0.1330},
            rotation = {0.0, 0.0, 180.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = true,
            minimumOffSet = {0.1740, 0.0, 0.0},
            maxOffSet = true,
            maximumOffSet = {1.3650, 0.9340, 0.1330},
            controls = {
                [208] = {
                    movementType = "move",
                    axis = 1,
                    movementAmount = 0.005,
                },
                [207] = {
                    movementType = "move",
                    axis = 1,
                    movementAmount = -0.005,
                },
            }
        },
        {
            id = "OutRigger4",
            model = `outrigger`,
            isLadder = false,
            attachTo = "vehicle",
            defaultOffSet = {0.1740, -3.3960, 0.1330},
            offSet = {0.17401, -3.3960, 0.1330},
            rotation = {0.0, 0.0, 180.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = true,
            minimumOffSet = {0.17401, 0.0, 0.0},
            maxOffSet = true,
            maximumOffSet = {1.3650, -3.3960, 0.1330},
            controls = {
                [208] = {
                    movementType = "move",
                    axis = 1,
                    movementAmount = 0.005,
                },
                [207] = {
                    movementType = "move",
                    axis = 1,
                    movementAmount = -0.005,
                },
            }
        },
        {
            id = "Foot1",
            model = `foot`,
            isLadder = false,
            attachTo = "OutRigger1",
            defaultOffSet = {-0.8800, 0.0, -0.8100},
             offSet = {-0.8800, 0.0, -0.8100},
            rotation = {0.0, 0.0, 0.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = true,
            minimumOffSet = {-0.8800, 0.0, -1.0100},
            maxOffSet = true,
            maximumOffSet = {-0.8800, 0.0, -0.8100},
            controls = {
                [121] = {
                    movementType = "move",
                    axis = 3,
                    movementAmount = 0.002,
                },
                [212] = {
                    movementType = "move",
                    axis = 3,
                    movementAmount = -0.002,
                },
            }
        },
        {
            id = "Foot2",
            model = `foot`,
            isLadder = false,
            attachTo = "OutRigger2",
            defaultOffSet = {-0.8800, 0.0, -0.8100},
             offSet = {-0.8800, 0.0, -0.8100},
            rotation = {0.0, 0.0, 0.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = true,
            minimumOffSet = {-0.8800, 0.0, -1.0100},
            maxOffSet = true,
            maximumOffSet = {-0.8800, 0.0, -0.8100},
            controls = {
                [121] = {
                    movementType = "move",
                    axis = 3,
                    movementAmount = 0.002,
                },
                [212] = {
                    movementType = "move",
                    axis = 3,
                    movementAmount = -0.002,
                },
            }
        },
        {
            id = "Foot3",
            model = `foot`,
            isLadder = false,
            attachTo = "OutRigger3",
            defaultOffSet = {-0.8800, 0.0, -0.8100},
             offSet = {-0.8800, 0.0, -0.8100},
            rotation = {0.0, 0.0, 0.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = true,
            minimumOffSet = {-0.8800, 0.0, -1.0100},
            maxOffSet = true,
            maximumOffSet = {-0.8800, 0.0, -0.8100},
            controls = {
                [121] = {
                    movementType = "move",
                    axis = 3,
                    movementAmount = 0.002,
                },
                [212] = {
                    movementType = "move",
                    axis = 3,
                    movementAmount = -0.002,
                },
            }
        },
        {
            id = "Foot4",
            model = `foot`,
            isLadder = false,
            attachTo = "OutRigger4",
            defaultOffSet = {-0.8800, 0.0, -0.8100},
            offSet = {-0.8800, 0.0, -0.8100},
            rotation = {0.0, 0.0, 0.0},
            minRotation = false,
            minimumRotation = {0.0, 0.0, 0.0},
            maxRotation = false,
            maximumRotation = {0.0, 0.0, 0.0},
            minOffSet = true,
            minimumOffSet = {-0.8800, 0.0, -1.0100},
            maxOffSet = true,
            maximumOffSet = {-0.8800, 0.0, -0.8100},
            controls = {
                [121] = {
                    movementType = "move",
                    axis = 3,
                    movementAmount = 0.002,
                },
                [212] = {
                    movementType = "move",
                    axis = 3,
                    movementAmount = -0.002,
                },
            }
        },
    }
}

addVehicle(firetruk)